// Can be overridden at compile time
#ifndef HASHTABLE_DEFAULT_CAPACITY
#define HASHTABLE_DEFAULT_CAPACITY (512)
#endif

#ifndef HASHTABLE_DEFAULT_MAX_LOAD_FACTOR
#define HASHTABLE_DEFAULT_MAX_LOAD_FACTOR (0.75)
#endif